config/routes.rb
Freeochart::Application.routes.draw do

  get "/ochart/company/company_searchComp.do"  => "proxy#comp"
  get "/bids/bids/bids_findBidsByCondition.do" => "proxy#bid"

  resources :comps
  resources :ocharts
  resources :bids

  

end

app/models/comp.rb
class Comp < ActiveRecord::Base
	# attr_accessible :comp_id, :comp_name, :area_code, :tel, :www, :brief
end

app/controllers/comps_controller.rb
class CompsController < ApplicationController
  before_action :set_comp, only: [:show, :edit, :update, :destroy]

  # GET /comps
  # GET /comps.json
  def index
    @comps = Comp.all
  end

  # GET /comps/1
  # GET /comps/1.json
  def show
  end

  # GET /comps/new
  def new
    @comp = Comp.new
  end

  # GET /comps/1/edit
  def edit
  end

  # POST /comps
  # POST /comps.json
  def create
    @comp = Comp.new(comp_params)

    respond_to do |format|
      if @comp.save
        format.html { redirect_to @comp, notice: 'Comp was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comp }
      else
        format.html { render action: 'new' }
        format.json { render json: @comp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comps/1
  # PATCH/PUT /comps/1.json
  def update
    respond_to do |format|
      if @comp.update(comp_params)
        format.html { redirect_to @comp, notice: 'Comp was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comps/1
  # DELETE /comps/1.json
  def destroy
    @comp.destroy
    respond_to do |format|
      format.html { redirect_to comps_url }
      format.json { head :no_content }
    end
  end

  # 接口入口
  def comp
    operation = params[:operation]
    if operation == "search"
      key = params[:name]
      search_companys(key)
    elsif operation == "get"
      comp_id = params[:comp_id]
      get_company(comp_id)
    else
      all_companys
    end
  end

  # 获取所有公司
  def all_companys
    comps = Comp.all
    render json: comps
  end

  # 搜索公司
  def search_companys(key)
    p key
    comps = Comp.where("upper(comp_name) like upper('%#{key}%')")
    render json: comps
  end

  # 获取公司
  def get_company(comp_id)
    comps = Comp.where(["comp_id=?", comp_id])
    comp = comps.first

    if comp.nil?
      render json: nil
      return
    end

    company = {
      comp_id:  comp[:comp_id],
      comp_name:comp[:comp_name],
      area_code:comp[:area_code],
      tel:      comp[:tel],
      www:      comp[:www],
      brief:    comp[:brief],
    }

    company_ocharts = Array.new

    ocharts = Ochart.where(["comp_id=?", comp_id])
    ocharts.each do |var|
      company_ocharts.push({ochart_id:var[:ochart_id], department_name:var[:department_name], parent_id:var[:parent_id]})
    end
    company[:ochart] = company_ocharts

    render json: company
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comp
      @comp = Comp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comp_params
      params.require(:comp).permit(:comp_id, :comp_name, :area_code, :tel, :www, :brief)
    end
end

app/helpers/comps_helper.rb
module CompsHelper
end

app/views/comps/_form.html.erb
<%= form_for(@comp) do |f| %>
  <% if @comp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comp.errors.count, "error") %> prohibited this comp from being saved:</h2>

      <ul>
      <% @comp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comp_id %><br>
    <%= f.text_field :comp_id %>
  </div>
  <div class="field">
    <%= f.label :comp_name %><br>
    <%= f.text_field :comp_name %>
  </div>
  <div class="field">
    <%= f.label :area_code %><br>
    <%= f.text_field :area_code %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :www %><br>
    <%= f.text_field :www %>
  </div>
  <div class="field">
    <%= f.label :brief %><br>
    <%= f.text_field :brief %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comps/edit.html.erb
<h1>Editing comp</h1>

<%= render 'form' %>

<%= link_to 'Show', @comp %> |
<%= link_to 'Back', comps_path %>

app/views/comps/index.html.erb
<h1>Listing comps</h1>

<table>
  <thead>
    <tr>
      <th>Comp</th>
      <th>Comp name</th>
      <th>Area code</th>
      <th>Tel</th>
      <th>Www</th>
      <th>Brief</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comps.each do |comp| %>
      <tr>
        <td><%= comp.comp_id %></td>
        <td><%= comp.comp_name %></td>
        <td><%= comp.area_code %></td>
        <td><%= comp.tel %></td>
        <td><%= comp.www %></td>
        <td><%= comp.brief %></td>
        <td><%= link_to 'Show', comp %></td>
        <td><%= link_to 'Edit', edit_comp_path(comp) %></td>
        <td><%= link_to 'Destroy', comp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comp', new_comp_path %>

app/views/comps/new.html.erb
<h1>New comp</h1>

<%= render 'form' %>

<%= link_to 'Back', comps_path %>

app/views/comps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comp:</strong>
  <%= @comp.comp_id %>
</p>

<p>
  <strong>Comp name:</strong>
  <%= @comp.comp_name %>
</p>

<p>
  <strong>Area code:</strong>
  <%= @comp.area_code %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @comp.tel %>
</p>

<p>
  <strong>Www:</strong>
  <%= @comp.www %>
</p>

<p>
  <strong>Brief:</strong>
  <%= @comp.brief %>
</p>

<%= link_to 'Edit', edit_comp_path(@comp) %> |
<%= link_to 'Back', comps_path %>