config/routes.rb
Freeochart::Application.routes.draw do

  get "/ochart/company/company_searchComp.do"  => "proxy#comp"
  get "/bids/bids/bids_findBidsByCondition.do" => "proxy#bid"

  resources :comps
  resources :ocharts
  resources :bids

  

end

app/models/ochart.rb
class Ochart < ActiveRecord::Base
end

app/controllers/ocharts_controller.rb
class OchartsController < ApplicationController
  before_action :set_ochart, only: [:show, :edit, :update, :destroy]

  # GET /ocharts
  # GET /ocharts.json
  def index
    @ocharts = Ochart.all
  end

  # GET /ocharts/1
  # GET /ocharts/1.json
  def show
  end

  # GET /ocharts/new
  def new
    @ochart = Ochart.new
  end

  # GET /ocharts/1/edit
  def edit
  end

  # POST /ocharts
  # POST /ocharts.json
  def create
    @ochart = Ochart.new(ochart_params)

    respond_to do |format|
      if @ochart.save
        format.html { redirect_to @ochart, notice: 'Ochart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ochart }
      else
        format.html { render action: 'new' }
        format.json { render json: @ochart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ocharts/1
  # PATCH/PUT /ocharts/1.json
  def update
    respond_to do |format|
      if @ochart.update(ochart_params)
        format.html { redirect_to @ochart, notice: 'Ochart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ochart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ocharts/1
  # DELETE /ocharts/1.json
  def destroy
    @ochart.destroy
    respond_to do |format|
      format.html { redirect_to ocharts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ochart
      @ochart = Ochart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ochart_params
      params.require(:ochart).permit(:ochart_id, :department_name, :parent_id, :comp_id)
    end
end

app/helpers/ocharts_helper.rb
module OchartsHelper
end

app/views/ocharts/_form.html.erb
<%= form_for(@ochart) do |f| %>
  <% if @ochart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ochart.errors.count, "error") %> prohibited this ochart from being saved:</h2>

      <ul>
      <% @ochart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ochart_id %><br>
    <%= f.text_field :ochart_id %>
  </div>
  <div class="field">
    <%= f.label :department_name %><br>
    <%= f.text_field :department_name %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.text_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :comp_id %><br>
    <%= f.text_field :comp_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ocharts/edit.html.erb
<h1>Editing ochart</h1>

<%= render 'form' %>

<%= link_to 'Show', @ochart %> |
<%= link_to 'Back', ocharts_path %>

app/views/ocharts/index.html.erb
<h1>Listing ocharts</h1>

<table>
  <thead>
    <tr>
      <th>Ochart</th>
      <th>Department name</th>
      <th>Parent</th>
      <th>Comp</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ocharts.each do |ochart| %>
      <tr>
        <td><%= ochart.ochart_id %></td>
        <td><%= ochart.department_name %></td>
        <td><%= ochart.parent_id %></td>
        <td><%= ochart.comp_id %></td>
        <td><%= link_to 'Show', ochart %></td>
        <td><%= link_to 'Edit', edit_ochart_path(ochart) %></td>
        <td><%= link_to 'Destroy', ochart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ochart', new_ochart_path %>

app/views/ocharts/new.html.erb
<h1>New ochart</h1>

<%= render 'form' %>

<%= link_to 'Back', ocharts_path %>

app/views/ocharts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ochart:</strong>
  <%= @ochart.ochart_id %>
</p>

<p>
  <strong>Department name:</strong>
  <%= @ochart.department_name %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @ochart.parent_id %>
</p>

<p>
  <strong>Comp:</strong>
  <%= @ochart.comp_id %>
</p>

<%= link_to 'Edit', edit_ochart_path(@ochart) %> |
<%= link_to 'Back', ocharts_path %>